apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: coredns-svc-lb-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: core-dns
spec:
  loadBalancerIP: 172.17.255.3
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 53
    targetPort: 53
