apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-viewer
  namespace: prometheus
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: ""
roleRef:
  kind: Role
  name: viewer
  apiGroup: ""