apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-cluster
  namespace: default
subjects:
- kind: ServiceAccount
  name: bob
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: ""