apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec: 
  initContainers:
  - name: generate-index-html
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}
  - name: web-drozd
  containers:
    name: web-app
    image: drozdnikita/drozd_web_app:1.0.0
    volumeMounts:
    - name: app
      mountPath: /app

